### ISSUE TITLE
window.PaystackPlugin.chargeCard is not a function

### ISSUE THREAD

**Issue by generalzodo** [tolu360/Cordova-Plugin-Paystack#10]
I cant seem to get the plugin working. it always returns 'window.PaystackPlugin.chargeCard is not a function', please what am I doing wrong

**Comment by cozzbie** [comment]
Can you please show some code so that we at least have a take off point?

**Comment by tolu360** [comment]
@generalzodo First off - the plugin just got updated, consult the README for installation workaround, usage and changes. Remove the old version by running cordova plugin remove cordova-plugin-paystack and then add it back again to pull in the latest version by running cordova plugin add cordova-plugin-paystack.

Remember to build and run your app again: cordova run android|ios. Let me know if you still have issues afterwards.

Cheers!

**Comment by tolu360** [comment]
@cozzbie - Pls, consult [usage examples](https://github.com/tolu360/cordova-plugin-paystack#3-usage) in the README, they are copied off of my test app.

**Comment by cozzbie** [comment]
Aiit. Thanks @tolu360

**Comment by blinks32** [comment]
Hi, @tolu360 i'm on ionic 3.5 and have set everything up as explained, but i keep getting the error above. please what i'm i doing wrong actually.

**Config.Xml**
```
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.playheavens.taxihub" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Taxihub</name>
    <description>An awesome Ionic/Cordova app.</description>
    <author email="hi@ionicframework" href="http://ionicframework.com/">Ionic Framework Team</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <preference name="loadUrlTimeoutValue" value="40000" />
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashScreenDelay" value="4000" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="FadeSplashScreen" value="false" />
    <preference name="FadeSplashScreenDuration" value="3000" />
    <preference name="SplashScreenBackgroundColor" value="0xFFFFFFFF" />
    <preference name="SplashScreen" value="screen" />
    <universal-links>
        <host name="tgp38.app.goo.gl" scheme="https" />
        <host name="taxi-59a68.firebaseapp.com" scheme="https">
            <path url="/__/auth/callback" />
        </host>
    </universal-links>
    <feature name="StatusBar">
        <param name="ios-package" onload="true" value="CDVStatusBar" />
    </feature>
    <allow-navigation href="http://192.168.145.1:8100" />
    <allow-navigation href="http://192.168.8.100:8100" />
    <engine name="android" spec="^6.2.3" />
    <plugin name="cordova-android-support-gradle-release" spec="0.0.2" />
    <plugin name="cordova-plugin-browsertab" spec="^0.2.0" />
    <plugin name="cordova-plugin-buildinfo" spec="^1.1.0" />
    <plugin name="cordova-plugin-device" spec="^1.1.6" />
    <plugin name="cordova-plugin-geolocation" spec="^2.0.0" />
    <plugin name="cordova-plugin-http" spec="^1.2.0" />
    <plugin name="cordova-plugin-inappbrowser" spec="^1.7.1" />
    <plugin name="cordova-plugin-mauron85-background-geolocation" spec="^2.2.5" />
    <plugin name="cordova-plugin-network-information" spec="^1.3.3" />
    <plugin name="cordova-plugin-paystack" spec="^3.1.0" />
    <plugin name="cordova-plugin-request-location-accuracy" spec="^2.2.1" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.0.3" />
    <plugin name="cordova-plugin-statusbar" spec="^2.2.3" />
    <plugin name="cordova-plugin-stripe" spec="^1.4.1" />
    <plugin name="cordova-plugin-vibration" spec="^2.1.5" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.2" />
    <plugin name="cordova-universal-links-plugin" spec="^1.2.1" />
    <plugin name="cordova.plugins.diagnostic" spec="^3.6.5" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    <plugin name="mx.ferreyra.callnumber" spec="~0.0.2" />
</widget>
```

**Comment by cozzbie** [comment]
Maybe I can be of help here.

Several problems could be taken from your setup but I don't want to jump to conclusions.

1. Are you including the paystack config variables in your `config.xml` file and intentionally removed it for security purposes? If yes...then check for what your `window.Paystack` variable outputs.

2. I really hope you are experimenting with this on a device and not in your browser.

**Comment by blinks32** [comment]
Yes i did, I'm getting this error from an android device. I didn't remove the plugin, its right there in my configuration file.

**Comment by blinks32** [comment]
Hi @cozzbie how did you run this on ionic 3, its there a step i can follow based on your setup?

**Comment by cozzbie** [comment]
I followed the README. What does your `console.log(window.PaystackPlugin)` show you?

**Comment by blinks32** [comment]
window.PaystackPlugin.chargeCard is not a function

**Comment by blinks32** [comment]
sorry for that wrong answer. I get Undefined when i run with console

**Comment by blinks32** [comment]
Thanks @cozzbie , **problem solved** i did this
```
 pay() {
  this.platform.ready().then(() => {
    // let PayStackClient = window['paystack'] || [];
    (<any>window).window.PaystackPlugin.chargeCard(
      (resp) => {
        // A valid one-timme-use token is obtained, do your thang!
        console.log('charge successful: ', resp);
      },
      (resp) => {
        // Something went wrong, oops - perhaps an invalid card.
        console.log('charge failed: ', resp);
      },
      {
        cardNumber: '4123450131001381', 
        expiryMonth: '10', 
        expiryYear: '17', 
        cvc: '883',
        email: 'chargeIOS@master.dev',
        amountInKobo: 150000,
        subAccount: 'ACCT_pz61jjjsslnx1d9',
    });
  })

  //console.log((<any>window).window.PaystackPlugin)
  } 
```

**Comment by cozzbie** [comment]
Dope. Well done.

**Comment by solomom399** [comment]
Hello @tolu360, i'm using the Paystack cordova plugin for my phonegap app but i'm getting a response of "No Public key found, please set the Public key", i've actually add the Public key to the config.xml, although it's a test mode public key...Please what do i need to do to make it see my Public key and make the transaction successful.

Thanks.
<?xml version="1.0" encoding="UTF-8"?>


<widget xmlns     = "http://www.w3.org/ns/widgets"
        xmlns:gap = "http://phonegap.com/ns/1.0"
        id        = "com.payment.payment"
        version   = "1.0.0"
        xmlns:android="http://schemas.android.com/apk/res/android">

    <name>PAYMENT</name>

    <description>
        Payment
    </description>

    <content src="index.html" />


    
    <preference name="DisallowOverscroll" value="true"/>
    <preference name="android-minSdkVersion" value="14"/>
    <preference name="SplashScreenDelay" value="1000"/>
    <preference name="StatusBarOverlaysWebView" value="true" />
    <preference name="StatusBarBackgroundColor" value="#a51c38" />
    <preference name="StatusBarStyle" value="blacktranslucent" />

    

    <plugin name="cordova-plugin-dialogs"             source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-network-information" source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-splashscreen"        source="npm" spec="~3.2.1" />
    <plugin name="cordova-plugin-statusbar"           source="npm" spec="~2.1.2" />

    <gap:plugin name="cordova-plugin-paystack" source="npm" />


    <icon src="icon.png" />

    <icon gap:platform="android" gap:qualifier="ldpi" src="res/icons/android/icon-36-ldpi.png" />
    <icon gap:platform="android" gap:qualifier="mdpi" src="res/icons/android/icon-48-mdpi.png" />
    <icon gap:platform="android" gap:qualifier="hdpi" src="res/icons/android/icon-72-hdpi.png" />
    <icon gap:platform="android" gap:qualifier="xhdpi" src="res/icons/android/icon-96-xhdpi.png" />
    <icon gap:platform="android" gap:qualifier="xxhdpi" src="res/icons/android/icon-144-xxhdpi.png" />
    <icon gap:platform="android" gap:qualifier="xxxhdpi" src="res/icons/android/icon-192-xxxhdpi.png" />

    <splash src="splash.png" />


    <splash gap:platform="android" gap:qualifier="land-hdpi" src="res/screens/android/screen-hdpi-landscape.png" />
    <splash gap:platform="android" gap:qualifier="land-ldpi" src="res/screens/android/screen-ldpi-landscape.png" />
    <splash gap:platform="android" gap:qualifier="land-mdpi" src="res/screens/android/screen-mdpi-landscape.png" />
    <splash gap:platform="android" gap:qualifier="land-xhdpi" src="res/screens/android/screen-xhdpi-landscape.png" />
    <splash gap:platform="android" gap:qualifier="port-hdpi" src="res/screens/android/screen-hdpi-portrait.png" />
    <splash gap:platform="android" gap:qualifier="port-ldpi" src="res/screens/android/screen-ldpi-portrait.png" />
    <splash gap:platform="android" gap:qualifier="port-mdpi" src="res/screens/android/screen-mdpi-portrait.png" />
    <splash gap:platform="android" gap:qualifier="port-xhdpi" src="res/screens/android/screen-xhdpi-portrait.png" />

    
    <access origin="*" />
    

    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />

        <config-file target="AndroidManifest.xml" parent="application">
            <meta-data android:name="co.paystack.android.PublicKey" android:value="pk_test_627b3212869ed34b3c5dee07082de6ece430cd6a"/>
        </config-file>
        

    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>

</widget>

**Comment by solomom399** [comment]
Here is my config.xml 

<?xml version="1.0" encoding="UTF-8"?>


<widget xmlns     = "http://www.w3.org/ns/widgets"
        xmlns:gap = "http://phonegap.com/ns/1.0"
        id        = "com.payment.payment"
        version   = "1.0.0"
        xmlns:android="http://schemas.android.com/apk/res/android">

    <name>PAYMENT</name>

    <description>
        Payment
    </description>

    <content src="index.html" />


    
    <preference name="DisallowOverscroll" value="true"/>
    <preference name="android-minSdkVersion" value="14"/>
    <preference name="SplashScreenDelay" value="1000"/>
    <preference name="StatusBarOverlaysWebView" value="true" />
    <preference name="StatusBarBackgroundColor" value="#a51c38" />
    <preference name="StatusBarStyle" value="blacktranslucent" />

    

    <plugin name="cordova-plugin-dialogs"             source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-network-information" source="npm" spec="~1.2.0" />
    <plugin name="cordova-plugin-splashscreen"        source="npm" spec="~3.2.1" />
    <plugin name="cordova-plugin-statusbar"           source="npm" spec="~2.1.2" />

    <gap:plugin name="cordova-plugin-paystack" source="npm" />


    <icon src="icon.png" />

    <icon gap:platform="android" gap:qualifier="ldpi" src="res/icons/android/icon-36-ldpi.png" />
    <icon gap:platform="android" gap:qualifier="mdpi" src="res/icons/android/icon-48-mdpi.png" />
    <icon gap:platform="android" gap:qualifier="hdpi" src="res/icons/android/icon-72-hdpi.png" />
    <icon gap:platform="android" gap:qualifier="xhdpi" src="res/icons/android/icon-96-xhdpi.png" />
    <icon gap:platform="android" gap:qualifier="xxhdpi" src="res/icons/android/icon-144-xxhdpi.png" />
    <icon gap:platform="android" gap:qualifier="xxxhdpi" src="res/icons/android/icon-192-xxxhdpi.png" />

    <splash src="splash.png" />


    <splash gap:platform="android" gap:qualifier="land-hdpi" src="res/screens/android/screen-hdpi-landscape.png" />
    <splash gap:platform="android" gap:qualifier="land-ldpi" src="res/screens/android/screen-ldpi-landscape.png" />
    <splash gap:platform="android" gap:qualifier="land-mdpi" src="res/screens/android/screen-mdpi-landscape.png" />
    <splash gap:platform="android" gap:qualifier="land-xhdpi" src="res/screens/android/screen-xhdpi-landscape.png" />
    <splash gap:platform="android" gap:qualifier="port-hdpi" src="res/screens/android/screen-hdpi-portrait.png" />
    <splash gap:platform="android" gap:qualifier="port-ldpi" src="res/screens/android/screen-ldpi-portrait.png" />
    <splash gap:platform="android" gap:qualifier="port-mdpi" src="res/screens/android/screen-mdpi-portrait.png" />
    <splash gap:platform="android" gap:qualifier="port-xhdpi" src="res/screens/android/screen-xhdpi-portrait.png" />

    
    <access origin="*" />
    

    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />

        <config-file target="AndroidManifest.xml" parent="application">
            <meta-data android:name="co.paystack.android.PublicKey" android:value="pk_test_627b3212869ed34b3c5dee07082de6ece430cd6a"/>
        </config-file>
        

    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>

</widget>
