### ISSUE TITLE
Update Plugin

### ISSUE THREAD

**Issue by adewaleadeoye** [tolu360/Cordova-Plugin-Paystack#11]
Hi,
Nice work on this plugin. I am currently making use of this it in a project. However, the paystack guys says the plugin needs to be updated for it to work properly.

Please a lot depends on it.

Kindly look into this and help bring it up to date. Would not mind helping out if possible.

**Comment by tolu360** [comment]
Hey @adewaleadeoye, so the plugin just got updated (to version 3.1.0) - please pay close attention to the README, there's been a few changes you need to be aware of.

To get started, remove the old version by running `cordova plugin remove cordova-plugin-paystack` and then add it back again to pull in the latest version by running `cordova plugin add cordova-plugin-paystack`.

Remember to build and run your app again: `cordova run android|ios`.

Cheers!

**Comment by adewaleadeoye** [comment]
Thanks

On Friday, June 9, 2017, 9:54:40 PM GMT+1, Tolu Olowu <notifications@github.com> wrote:


Hey @adewaleadeoye, so the plugin just got updated (to version 3.1.0) - please pay close attention to the README, there's been a few changes you need to be aware of.

To get started, remove the old version by running cordova plugin remove cordova-plugin-paystack and then add it back again to pull in the latest version by running cordova plugin add cordova-plugin-paystack.

Remember to build and run your app again: cordova run android|ios.

Cheers!
