### ISSUE TITLE
No Public key found, please set the Public key

### ISSUE THREAD

**Issue by solomom399** [tolu360/Cordova-Plugin-Paystack#13]
Please help me, i'm getting the response "No Public key found, please set the Public key" from cordova-plugin-paystack...i'm using a test mode Public key. I'll appreciate any idea of how to make it work successfully.

Thanks.

**Comment by tolu360** [comment]
First off, ensure you are testing on an Android emulator/ iOS simulator - never in a web browser.

On which platform are you having this issue? Which version of the plugin are you working it? Did you  remember to build (run `cordova build android/ios`) again after configuring your config.xml?

Cheers

**Comment by solomom399** [comment]
Good day @tolu360, i'm actually testing the app on an android phone and i'm using the current version.

Thanks.

**Comment by tolu360** [comment]
You should be fine Solomon, can't say why you are not.

For the version I asked earlier, I need you to supply actual version numbers - add your cordova version number in as well.

And **after** you run the `build` command, look in `/platforms/android/AndroidManifest.xml`, within the `application` tag, do you see the exact same line you added in your config.xml - a line like below?

```xml
<meta-data android:name="co.paystack.android.PublicKey" android:value="pk_test_aa65a1064hfhdjjdkdkdkdkeueyeyejek" />
```
If you see that line after running the `build` command, you shouldn't have that error. 

**NP:** Don't manually edit that file - your changes get overwritten each time you build your app.

**Comment by solomom399** [comment]
I'm building with the latest phonegap build https://build.phonegap.com...i checked the app  AndroidManifest.xml on my phone but there's nothing like the code below in it

<meta-data android:name="co.paystack.android.PublicKey" android:value="pk_test_aa65a1064hfhdjjdkdkdkdkeueyeyejek" />

I'll appreciate any code example to guild me through.

Thank you so much sir for your support.

**Comment by solomom399** [comment]
Here is the response from the app

![img_20170928_113729_315](https://user-images.githubusercontent.com/19938801/30965756-56c23fd2-a40b-11e7-8dd1-249180746aa6.jpg)

**Comment by tolu360** [comment]
Hey, I don't know if PhoneGap Build service now supports Cordova build hooks (this plugin uses build hooks) - if it does not, that would break the plugin unless you can figure out a way to add the `meta-data` tag above to your app AndroidManifest.xml.

Unfortunately, I can't help any further. You can always try to set up and build on your local machine though. All the best

**Comment by solomom399** [comment]
Ok sir, thanks so much.

**Comment by tolu360** [comment]
U welcome, not a problem.
