### ISSUE TITLE
Typescript Error Property 'PaystackPlugin' does not exist on type 'Window'.

### ISSUE THREAD

**Issue by cititech** [tolu360/Cordova-Plugin-Paystack#14]
I followed the instruction in your article in an attempt to implement paystack payment integration with my app, but I got the following error message, what do you think could be wrong

```
Typescript Error
Property 'PaystackPlugin' does not exist on type 'Window'.
C:/Projects/WorkMan/src/pages/paystack/paystack.ts
  
window.PaystackPlugin.chargeCard(
      function(resp) {

thank you in advance

**Comment by bot101** [comment]
I see you are using Ionic 2+. You'll have to import PaystackPlugin from its folder to use it. Instructions available here are valid only for Ionic 1 and other Cordova based platforms.

Do something like `import * as PaystackPlugin from 'path/to/paystack;'`. `path/to/paystack` is most likely going to be in `node_modules`. I haven't used Paystack in Ionic 2, so this is the much I can assist with.

**Comment by blinks32** [comment]
@cititech  check out https://github.com/blinks32/ionic3-paystack-plugin-setup

**Comment by cititech** [comment]
Hi guys,
it works great, thank you
    On Wednesday, October 25, 2017, 6:56:27 AM GMT+1, Chinedu Etoh <notifications@github.com> wrote:  
 
 
@cititech check out https://github.com/blinks32/ionic3-paystack-plugin-setup
