### ISSUE TITLE
Feature request for payment instrument tokenizing

### ISSUE THREAD

**Issue by bot101** [tolu360/Cordova-Plugin-Paystack#15]
There isn't any functionality to add a card without the user having to make a payment. This is extremely useful where the user already has a card used in making a previous payment, but would like to change it before making another payment.

Essentially, what I am asking is a means to tokenize a card from the plugin using the provided Paystack endpoint available [here](https://developers.paystack.co/reference#charge-tokenize). This would be a good replacement for `PaystackPlugin.getToken()` which has been removed. Attempting to collect user card details then using the endpoint from a server or mobile app is a security risk, and sensitive information can be given away.

**Comment by tolu360** [comment]
I want to believe @bot101 is actually a human - LOL! Please note that only feature requests based off of features available on the underlying Paystack SDKs (Android & iOS) can fly here. Tokenisation was deprecated by the guys at Paystack for reasons best known to them!

You can make this request on https://github.com/PaystackHQ/paystack-android or https://github.com/PaystackHQ/paystack-ios or on the Paystack Slack channels. 

Cheers!

**Comment by bot101** [comment]
Haha! @bot101is definitely human. I'll sadly have to live with this, thanks for the clarification.
