### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by vinaysrivastavacct** [tolu360/Cordova-Plugin-Paystack#16]
Hello,

I tried to install through
cordova plugin add cordova-plugin-paystack 
npm CLI,

It gives error 
failed to fetch plugin github.com/dpa99c/cordova-custom-config.git via registry.
detailed error attached
![errormessage](https://user-images.githubusercontent.com/30234507/31900743-249872ec-b83d-11e7-95cf-14ad18723b75.jpg)

**Comment by blinks32** [comment]
You could break this by doing this: 

`cordova plugin add cordova-custom-config`

Then:

`cordova plugin add cordova-plugin-paystack`

It was trying to fetch the dependency plugin `cordova-custom-config` but failed, maybe due a network problem. You can also comment this line:

`<dependency id="cordova-custom-config" url="https://github.com/dpa99c/cordova-custom-config.git"  />`

In `plugins\cordova-plugin-paystack\plugin.xml`. If You don't need the custom config installing again during build, It still works without the custom config, But i guess you should leave it.
