### ISSUE TITLE
Paystack Plugin Usage

### ISSUE THREAD

**Issue by mexxyyoung** [tolu360/Cordova-Plugin-Paystack#17]
Please, i have installed the plugin but stucked at the 'USAGE' aspect. Can you please help me out? I want to get the app to request for subscription fee before the app content could be seen

**Comment by mexxyyoung** [comment]
Please, i have installed the plugin but stucked at the 'USAGE' aspect. Can you please help me out? I want to get the app to request for subscription fee before the app content could be seen

**Comment by tolu360** [comment]
Hello @mexxyyoung, did you find any issues/problems with any methods/API provided by this plugin? You can find ample sample usage in the [README](https://github.com/tolu360/cordova-plugin-paystack#3-usage) with detailed instructions on how to go about handling subscriptions.

Specific issues regarding building apps with Cordova/PhoneGap and/or structuring app logic are outside the scope of this library. I'm sure you'd find further help on those platforms. Cheers!
