### ISSUE TITLE
BUILD FAILED on ":processDebugManifest"

### ISSUE THREAD

**Issue by biggjoe** [tolu360/Cordova-Plugin-Paystack#20]
I have successfully installed the plugin but it always fail on build with the attached image.
I have tried  adding 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml as suggested but it comes with another error that its not bound.

What could be the issue here?

![paystack_error](https://user-images.githubusercontent.com/24505989/36896301-6aadb162-1e12-11e8-99a5-512d298e46a6.jpg)

**Comment by tolu360** [comment]
Please check to make sure you have added `xmlns:android="http://schemas.android.com/apk/res/android"` to the `widget` tag of the `config.xml` file in the root of your project folder.

Then try to rebuild your project.

**Comment by biggjoe** [comment]
> Please check to make sure you have added xmlns:android="http://schemas.android.com/apk/res/android" to the widget tag of the config.xml file in the root of your project folder.


I did that.

**Comment by tolu360** [comment]
Also note that Cordova overwrites your direct edits to AndroidManifest.vml at build time so you should not directly add any lines to the file.
Above the lines setting up Paystack in `config.xml`, that is:
```xml
<config-file target="AndroidManifest.xml" parent="application">
      	<meta-data android:name="co.paystack.android.PublicKey" android:value="INSERT-PUBLIC-KEY-HERE"/>
    </config-file>
```
Try to add: 

```xml
<config-file target="AndroidManifest.xml" mode="add">
    <application tools:replace="android:value" />
</config-file>
```
Let me know if that changes the error message or fixes it.

**Comment by biggjoe** [comment]
Its something to do with the project.
I installed the plugin on another project directory without the fix you provided and it worked just fine.
I appreciate your help.
