### ISSUE TITLE
Build Failed while Building for IOS

### ISSUE THREAD

**Issue by Mercyware** [tolu360/Cordova-Plugin-Paystack#24]
Hi, i am experiencing an error while trying to run ionic application on device. 
The app works on Android Device and IOS emulator but show this errors while trying to run on a real ios device

`       
       Ld /Users/mac/Library/Developer/Xcode/DerivedData/dataluk_health- 
        gvvuybmobfghkcelqspquthdffdj/Build/Products/Debug-iphoneos/dataluk\ health.app/dataluk\health 
   normal armv7

    cd /Users/mac/Desktop/Dataluk2/platforms/ios

    export IPHONEOS_DEPLOYMENT_TARGET=9.0

    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -L/Users/mac/Library/Developer/Xcode/DerivedData/dataluk_health-gvvuybmobfghkcelqspquthdffdj/Build/Products/Debug-iphoneos -F/Users/mac/Library/Developer/Xcode/DerivedData/dataluk_health-gvvuybmobfghkcelqspquthdffdj/Build/Products/Debug-iphoneos -Fdataluk\ health/Plugins/cordova-plugin-paystack -filelist /Users/mac/Library/Developer/Xcode/DerivedData/dataluk_health-gvvuybmobfghkcelqspquthdffdj/Build/Intermediates.noindex/dataluk\ health.build/Debug-iphoneos/dataluk\ health.build/Objects-normal/armv7/dataluk\ health.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/dataluk_health-gvvuybmobfghkcelqspquthdffdj/Build/Intermediates.noindex/dataluk\ health.build/Debug-iphoneos/dataluk\ health.build/Objects-normal/armv7/dataluk\ health_lto.o -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC /Users/mac/Library/Developer/Xcode/DerivedData/dataluk_health-gvvuybmobfghkcelqspquthdffdj/Build/Products/Debug-iphoneos/libCordova.a -lz -framework MessageUI -framework CoreLocation -weak_framework WebKit -framework SystemConfiguration -weak_framework AudioToolbox -weak_framework AVFoundation -weak-lsqlite3 -framework CoreTelephony -framework Paystack -Xlinker -dependency_info -Xlinker /Users/mac/Library/Developer/Xcode/DerivedData/dataluk_health-gvvuybmobfghkcelqspquthdffdj/Build/Intermediates.noindex/dataluk\ health.build/Debug-iphoneos/dataluk\ health.build/Objects-normal/armv7/dataluk\ health_dependency_info.dat -o /Users/mac/Library/Developer/Xcode/DerivedData/dataluk_health-gvvuybmobfghkcelqspquthdffdj/Build/Products/Debug-iphoneos/dataluk\ health.app/dataluk\ health

     ld: warning: ignoring file dataluk health/Plugins/cordova-plugin- 
     paystack/Paystack.framework/Paystack, file was built for x86_64 which is not the architecture being 
      linked (armv7): dataluk health/Plugins/cordova-plugin-paystack/Paystack.framework/Paystack

      Undefined symbols for architecture armv7:

      "_OBJC_CLASS_$_PSTCKTransactionParams", referenced from:

      objc-class-ref in PaystackPlugin.o

      "_OBJC_CLASS_$_PSTCKAPIClient", referenced from:

      objc-class-ref in PaystackPlugin.o

    "_OBJC_CLASS_$_PSTCKCardParams", referenced from:

      objc-class-ref in PaystackPlugin.o

     "_OBJC_CLASS_$_PSTCKCardValidator", referenced from:

      objc-class-ref in PaystackPlugin.o

       "_OBJC_CLASS_$_Paystack", referenced from:

      objc-class-ref in PaystackPlugin.o

      (maybe you meant: _OBJC_CLASS_$_PaystackPlugin)

      ld: symbol(s) not found for architecture armv7

      clang: error: linker command failed with exit code 1 (use -v to see invocation)

`

**Comment by tolu360** [comment]
Hi, closing this as a stale issue, if you still have this issue on the latest version (3.2.0) and following the updated README, kindly open a new issue. Cheers!

**Comment by mykoman** [comment]
Hi I am experiencing this same error here. Could you help look into this please?

**Comment by ganiru** [comment]
@tolu360 how was this resolved? I'm experiencing the issue in my Ionic 3 app. I've already followed the instructions in the readme to no avail, even copied the Paystack.framework folder as instructed.
