### ISSUE TITLE
Publishable Key for Windows Platform

### ISSUE THREAD

**Issue by django101** [tolu360/Cordova-Plugin-Paystack#28]
Hi.

So for setting publishable key for android, we use 

`<platform name="android">
    ...
    <preference name="android-minSdkVersion" value="16" />
    <config-file target="AndroidManifest.xml" parent="application">
      	<meta-data android:name="co.paystack.android.PublicKey" android:value="INSERT-PUBLIC-KEY-HERE"/>
    </config-file>
</platform>`

While that for iOS 

`<platform name="ios">
    ...
    <preference name="publicKey" value="INSERT-PUBLIC-KEY-HERE" />
</platform>`

How would be do it for Windows Platform?

Thanks

**Comment by tolu360** [comment]
Hi,

Good question, the Windows platform is not currently supported as I don't own a Windows device. Do you think you can make a pull-request providing support for that platform?

Also there's a new version and a slight change to the setup you referenced above, ensure you catch up on that.

Cheers!
