### ISSUE TITLE
Possible cause of "Invalid token"

### ISSUE THREAD

**Issue by darmie** [tolu360/Cordova-Plugin-Paystack#6]
Hi,

Token generated by this plugin is being returned as invalid when I try to charge the token. 

```json
{"data":{"status":false,"message":"Invalid Token"}
```

What could be the cause? I didn't find any explanation on Paystack docs.

**Comment by tolu360** [comment]
I'm hoping it was a one-off occurrence, please try again. I just obtained and charged a `token` successfully few minutes ago. Also bear in mind you can only charge a token once - no re-use. If the issue persists, you can mention it on the Paystack `Slack channel` to see if anyone has had issues charging mobile tokens.

**Comment by darmie** [comment]
Yes you are right, it was a one off experience.
