### ISSUE TITLE
Error Building Application With Plugin

### ISSUE THREAD

**Issue by strateg2016** [tolu360/Cordova-Plugin-Paystack#8]
Hi. I have this issue when building with your plugin:

```
MSBUILD : cordova-build error : FAILURE: Build failed with an exception.
1>  FAILURE: Build failed with an exception.
1>
1>MSBUILD : cordova-build error : * What went wrong:
1>  * What went wrong:
1>MSBUILD : cordova-build error : A problem occurred configuring root project 'android'.
1>  A problem occurred configuring root project 'android'.
1>MSBUILD : cordova-build error : > Could not resolve all dependencies for configuration ':_debugCompile'.
1>  > Could not resolve all dependencies for configuration ':_debugCompile'.
1>MSBUILD : cordova-build error :  > Could not find co.paystack.android:paystack:2.1.2.
1>     > Could not find co.paystack.android:paystack:2.1.2.
1>MSBUILD : cordova-build error :  Searched in the following locations:
1>       Searched in the following locations:
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/co/paystack/android/paystack/2.1.2/paystack-2.1.2.pom
1>           https://repo1.maven.org/maven2/co/paystack/android/paystack/2.1.2/paystack-2.1.2.pom
1>MSBUILD : cordova-build error :  https://repo1.maven.org/maven2/co/paystack/android/paystack/2.1.2/paystack-2.1.2.jar
1>           https://repo1.maven.org/maven2/co/paystack/android/paystack/2.1.2/paystack-2.1.2.jar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/co/paystack/android/paystack/2.1.2/paystack-2.1.2.pom
1>           file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/co/paystack/android/paystack/2.1.2/paystack-2.1.2.pom
1>
1>  BUILD FAILED
1>
1>  Total time: 5.498 secs
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/co/paystack/android/paystack/2.1.2/paystack-2.1.2.jar
1>           file:/C:/Program Files (x86)/Android/android-sdk/extras/android/m2repository/co/paystack/android/paystack/2.1.2/paystack-2.1.2.jar
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/co/paystack/android/paystack/2.1.2/paystack-2.1.2.pom
1>           file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/co/paystack/android/paystack/2.1.2/paystack-2.1.2.pom
1>MSBUILD : cordova-build error :  file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/co/paystack/android/paystack/2.1.2/paystack-2.1.2.jar
1>           file:/C:/Program Files (x86)/Android/android-sdk/extras/google/m2repository/co/paystack/android/paystack/2.1.2/paystack-2.1.2.jar
1>MSBUILD : cordova-build error :  Required by:
1>       Required by:
1>MSBUILD : cordova-build error :  :android:unspecified
1>           :android:unspecified
1>
```

Any help would be deeply appreciated.

NB: Issue started yesterday. #MissionCritical

**Comment by tolu360** [comment]
Hi @strateg2016, I just ran a build with the current version of the plugin `(2.1.1)` with no issues - could not reproduce your issue. 

But lets try a few things: [ensure you have done everything I previous advised here](https://github.com/tolu360/cordova-plugin-paystack/issues/7#issuecomment-264813196)

Remove the plugin and add it again:

```bash
cordova plugin rm cordova-plugin-paystack
cordova plugin add cordova-plugin-paystack --save
```

Build your app again:

```bash
cordova build android
```

Let me know of any changes.

**Comment by strateg2016** [comment]
Hi @tolu360 . issue still persists.

I have already done all the prerequisites...as i have been using this plugin for my demo app. I built the app last on Friday. I had to make a few minor modifications on the app yesterday (texty stuff) and built. Boom. Apocalypse now. The version of the plugin is 2.1.1, but the maven repo is saying 2.1.2 Could this be the issue?

P.S: These are the links that were displayed:
[https://repo1.maven.org/maven2/co/paystack/android/paystack/2.1.2/paystack-2.1.2.pom](https://repo1.maven.org/maven2/co/paystack/android/paystack/2.1.2/paystack-2.1.2.pom)
[https://repo1.maven.org/maven2/co/paystack/android/paystack/2.1.2/paystack-2.1.2.jar](https://repo1.maven.org/maven2/co/paystack/android/paystack/2.1.2/paystack-2.1.2.jar)
[https://download.01.org/crosswalk/releases/crosswalk/android/maven2/co/paystack/android/paystack/2.1.2/paystack-2.1.2.pom](https://download.01.org/crosswalk/releases/crosswalk/android/maven2/co/paystack/android/paystack/2.1.2/paystack-2.1.2.pom)
[https://download.01.org/crosswalk/releases/crosswalk/android/maven2/co/paystack/android/paystack/2.1.2/paystack-2.1.2.jar](https://download.01.org/crosswalk/releases/crosswalk/android/maven2/co/paystack/android/paystack/2.1.2/paystack-2.1.2.jar)

**Comment by tolu360** [comment]
Sorry @strateg2016, these things happen. The underlying paystack android SDK is at version 2.1.2 which has nothing to do with the versioning of this plugin.

Try this first. Edit `/plugins/cordova-plugin-paystack/src/android/build.gradle` as follows:

Add the `repositories` block just above the `dependencies` like so:

```gradle
----

repositories {
    maven {
        url 'https://dl.bintray.com/paystack/maven/'
    }
}

dependencies {
----
}

```

Build your app again and let me know if anything changes.

As a last resort, create a  new blank cordova project, make the plugin work with it and thereafter, you can replace the `www` folder with that from your existing `www` folder.

**Comment by strateg2016** [comment]
Thanks. I eventually sorted out the issue.  The link you provided above was a guide, though the mirrored post [here](https://www.npmjs.com/package/cordova-plugin-paystack) is more up-to-date that your readMe. 

The readMe should be updated.

Thanks for the help, as always.

**Comment by tolu360** [comment]
Can you be more specific? What exactly did you do differently? What do you think is missing from the README?

**Comment by strateg2016** [comment]
After installing the plugin, there was a link, like a "more information" link that i clicked and it took me to [this page](https://www.npmjs.com/package/cordova-plugin-paystack). It was there that i saw this portion, after "FIXING BUILD ERROR (iOS):

```
****For Android Builds, have the following on your local build environment: 
Android SDK Tools: 25+ 
Android SDK Platform-tools: 25+ 
Android SDK Build-tools: 25+ 
SDK Platform: 25+ 
Android Support Repository: 39+
```
Urs, from the link u shared above, says:

```
Android SDK Tools: 24+
Android SDK Platform-tools: 24+
Android SDK Build-tools: 24+
SDK Platform: 24+
Android Support Repository: 39+
Android Support Library: 23+
```

and this was actually where my installation was. I just updated them to 25+ and it was fine.

I guess ur recommendation of the repositories block would work just as well, but most people just wanna install and start working. Changing the contents of the build.gradle is actually chronic for some noobs and intermediates.

In the ReadMe, you can put the 2 procedures the. The Repositories code block for 24+ and the direct one for the 25+

Thanks
