### ISSUE TITLE
Card pin now compulsory 

### ISSUE THREAD

**Issue by cozzbie** [tolu360/Cordova-Plugin-Paystack#9]
I was talking to a Paystack staff and they said pins are now compulsory. How does your plugin handle this?

**Comment by tolu360** [comment]
Hello @cozzbie, the plugin is fashioned after Paystack's official SDK demos - it should prompt you for PINs when necessary. Please use your test keys and a Verve card and see if it does. Let me have your feedback.

If there's been any recent updates on Paystack's end, then I'd need to update the plugin accordingly. Cheers.

**Comment by cozzbie** [comment]
Interesting. I will be trying to see how the pin requirement comes back. Thanks.

**Comment by cozzbie** [comment]
Just got back from speaking with a Paystack rep and they said tokenization has now been deprecated. They only do Charge and Authorization now. Any way around this using the Plugin? @tolu360

**Comment by tolu360** [comment]
@cozzbie You would have to use `PaystackPlugin.chargeCard()` or wait till I can update the plugin to parity with the latest Paystack SDKs

**Comment by cozzbie** [comment]
Okidoks. Will see how this works out. Thanks.

**Comment by tolu360** [comment]
Hey @cozzbie, so the plugin just got updated (to version 3.1.0) - please pay close attention to the README, there's been a few changes you need to be aware of. The plugin now has feature parity with the underlying Paystack SDKs.

To get started, remove the old version by running cordova plugin remove cordova-plugin-paystack and then add it back again to pull in the latest version by running cordova plugin add cordova-plugin-paystack.

Remember to build and run your app again: cordova run android|ios.

Cheers!

**Comment by cozzbie** [comment]
Thanks man. Will do
